//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MineGame {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MineGame.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is your move:.
        /// </summary>
        public static string COMMAND_PROMPT_TEXT {
            get {
                return ResourceManager.GetString("COMMAND_PROMPT_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid commands: up/u, down/d, right/r, left/l, exit.
        /// </summary>
        public static string COMMAND_REMINDER_TEXT {
            get {
                return ResourceManager.GetString("COMMAND_REMINDER_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GAME OVER. No lives remain..
        /// </summary>
        public static string FAIL_TEXT {
            get {
                return ResourceManager.GetString("FAIL_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You hit a mine!.
        /// </summary>
        public static string HIT_TEXT {
            get {
                return ResourceManager.GetString("HIT_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are at tile A1, you need to get to tile H8 whilst avoiding the mines. Good luck..
        /// </summary>
        public static string INTRO_TEXT {
            get {
                return ResourceManager.GetString("INTRO_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command not recognised..
        /// </summary>
        public static string INVALID_COMMAND_TEXT {
            get {
                return ResourceManager.GetString("INVALID_COMMAND_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t move that way! You are at the edge of the board..
        /// </summary>
        public static string INVALID_MOVE_TEXT {
            get {
                return ResourceManager.GetString("INVALID_MOVE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lives: .
        /// </summary>
        public static string LIVES_TEXT {
            get {
                return ResourceManager.GetString("LIVES_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your current location is: .
        /// </summary>
        public static string LOCATION_TEXT {
            get {
                return ResourceManager.GetString("LOCATION_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You made it to the finish!.
        /// </summary>
        public static string WIN_TEXT {
            get {
                return ResourceManager.GetString("WIN_TEXT", resourceCulture);
            }
        }
    }
}
